# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4abcec30c4b28e0a75fbdc6bad600a60f4807363edb1d29c94a92e6bf774a31bf0076694ffe4cee01599e24ad99c0e389e2fa2fc7b9a796419dfb9c281222e51
  api:
    access_token: CHANGE_ME
test:
  secret_key_base: cf837c51a85746e2a7e2ee6f2fa58b595d017e06749c6906619321878c53a4e4aef496dc18e55cc8ead3e7b61ba6d1e29ba37a11e2d58af4913c94b2cd80adef
  api_access_token: some-test-token
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api:
    access_token: CHANGE_ME
